.TH _PRINTF 3 19/March/2019 "0.32" "_printf man page"
.SH NAME
_printf \- format and print data from input
.SH SYNOPSIS
#include "holberton.h"

int _printf(const char *format, ...);

.B _printf \fB\fR\fIFORMAT\fR
.IR [\fIARGUMENT\fI] ...

.B _printf \fB\fR\fIOPTION\f

.SH DESCRIPTION

Print ARGURMENT(s) according to FORMAT, or execute according to OPTION:

\fB\-\-help\fR display this help and exit

\fB\-\-version\fR output version information and exit

FORMAT controls the output as in C _printf. Interpreted sequences are:

.B %
a % followed by a % will print a single %. Any other cases are not currently able to be handled

.B %c
will print a single character given as an argument.

.B %s
will print a string of any length given as an argument.

.B %d
and
.B %i
will both print out a number given as an argument. The number given can be positive or negative.

.B %b
will take an integer in as an argument, convert it to binary, and then print the number in binary form.

.B %r
will take a string as an argument, and print that string in reverse.

.B %R
will take a string as an argument, convert it to rot13, and print it.


.SH AUTHOR
Nick O'Keefe, Tywan Brooks
